### ISSUE TITLE
Cannot read property 'setEncoding' of undefined

### ISSUE THREAD

**Issue by claycephas** [bahamas10/node-sshp#5]
I'm getting the following error trying to run this:
```
sshp -f myhosts.txt "echo hi"
/Users/claya/.nvm/versions/node/v8.6.0/lib/node_modules/sshp/sshp.js:285
  child.stdout.setEncoding('utf-8');
              ^

TypeError: Cannot read property 'setEncoding' of undefined
    at processhost (/Users/claya/.nvm/versions/node/v8.6.0/lib/node_modules/sshp/sshp.js:285:15)
    at process (/Users/claya/.nvm/versions/node/v8.6.0/lib/node_modules/sshp/node_modules/async/lib/async.js:608:21)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

But running ssh directly works:
```
ssh -n host1 echo hi
hi
Killed by signal 1.
```

Environment:
```
$ node -v
v8.6.0
$ npm -v
5.3.0
$ sshp -v
0.4.3
```

**Comment by claycephas** [comment]
I was able to get it working by limiting the number of concurrent jobs with `-m 100`. But #6 will at least make it fail more gracefully.

**Comment by bahamas10** [comment]
Just an fyi, like how you don't need quotes around `echo hi` when calling `ssh` directly, you don't need the quotes around `echo hi` when calling `sshp`.
